SET(UMUNDOCORE_PREBUILT ${PROJECT_SOURCE_DIR}/../core/lib/${CMAKE_SYSTEM_NAME_LC}-${CMAKE_SYSTEM_PROCESSOR}/${CMAKE_CXX_COMPILER_ID_LC})

if(CMAKE_CROSSCOMPILING AND IOS)
	SET(CMAKE_FIND_LIBRARY_SUFFIXES .a)
	SET(UMUNDOCORE_PREBUILT ${CONTRIB_PREBUILT}/zeromq/ios/${CMAKE_SYSTEM_VERSION})
endif()

if(CMAKE_CROSSCOMPILING AND ANDROID)
	SET(CMAKE_FIND_LIBRARY_SUFFIXES .a)
	SET(UMUNDOCORE_PREBUILT ${CONTRIB_PREBUILT}/zeromq/android/${ANDROID_NDK_ABI_EXT})
endif()

FIND_PATH(UMUNDOCORE_INCLUDE_DIR connection/Publisher.h
  HINTS
  $ENV{UMUNDOCORE_INCLUDE_DIR}
  ../core/src
)

FIND_LIBRARY(UMUNDOCORE_LIBRARY 
  NAMES umundocore libumundocore
  HINTS
  $ENV{UMUNDOCORE_LIBRARY}
  ${UMUNDOCORE_PREBUILT}
)

FIND_LIBRARY(UMUNDOCORE_LIBRARY_DEBUG
  NAMES umundocore libumundocore
  HINTS
  $ENV{UMUNDOCORE_LIBRARY}
  ${UMUNDOCORE_PREBUILT}
)

# handle the QUIETLY and REQUIRED arguments and set OPENAL_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(umundo.core DEFAULT_MSG UMUNDOCORE_INCLUDE_DIR UMUNDOCORE_LIBRARY UMUNDOCORE_LIBRARY_DEBUG)
MARK_AS_ADVANCED(UMUNDOCORE_INCLUDE_DIR UMUNDOCORE_LIBRARY UMUNDOCORE_LIBRARY_DEBUG)
