# 
#
#
#

FIND_PATH(UMUNDO_INCLUDE_DIR umundo/core.h
  HINTS $ENV{UMUNDO_INCLUDE_DIR}
  PATH_SUFFIXES include
  PATHS
  /usr/local
)

FIND_LIBRARY(UMUNDO_CORE_LIBRARY 
  NAMES umundocore HINTS $ENV{UMUNDO_LIB_DIR}
  PATHS
  /usr/local
)

FIND_LIBRARY(UMUNDO_CORE_LIBRARY_DEBUG
  NAMES umundocore_d HINTS $ENV{UMUNDO_LIB_DIR}
  PATHS
  /usr/local
)

FIND_LIBRARY(UMUNDO_S11N_LIBRARY 
  NAMES umundoserial HINTS $ENV{UMUNDO_LIB_DIR}
  PATHS
  /usr/local
)

FIND_LIBRARY(UMUNDO_S11N_LIBRARY_DEBUG
  NAMES umundoserial_d HINTS $ENV{UMUNDO_LIB_DIR}
  PATHS
  /usr/local
)

FIND_LIBRARY(UMUNDO_RPC_LIBRARY 
  NAMES umundorpc HINTS $ENV{UMUNDO_LIB_DIR}
  PATHS
  /usr/local
)

FIND_LIBRARY(UMUNDO_RPC_LIBRARY_DEBUG
  NAMES umundorpc_d HINTS $ENV{UMUNDO_LIB_DIR}
  PATHS
  /usr/local
)

find_program(UMUNDO_PROTOBUF_RPC_EXECUTABLE 
	NAMES protoc-umundo-rpc protoc-umundo-rpc.exe
)

SET(UMUNDO_LIBRARIES optimized ${UMUNDO_CORE_LIBRARY})
LIST(APPEND UMUNDO_LIBRARIES optimized ${UMUNDO_S11N_LIBRARY})
LIST(APPEND UMUNDO_LIBRARIES optimized ${UMUNDO_RPC_LIBRARY})

SET(UMUNDO_LIBRARIES_DEBUG debug ${UMUNDO_CORE_LIBRARY_DEBUG})
LIST(APPEND UMUNDO_LIBRARIES_DEBUG debug ${UMUNDO_S11N_LIBRARY_DEBUG})
LIST(APPEND UMUNDO_LIBRARIES_DEBUG debug ${UMUNDO_RPC_LIBRARY_DEBUG})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(UMUNDO DEFAULT_MSG UMUNDO_CORE_LIBRARY)
MARK_AS_ADVANCED(UMUNDO_INCLUDE_DIR UMUNDO_CORE_LIBRARY UMUNDO_S11N_LIBRARY UMUNDO_RPC_LIBRARY UMUNDO_CORE_LIBRARY_DEBUG UMUNDO_S11N_LIBRARY_DEBUG UMUNDO_RPC_LIBRARY_DEBUG UMUNDO_INCLUDED_DIR)
