SET(PTHREAD_PREBUILT ${CONTRIB_PREBUILT}/pthread/${CMAKE_SYSTEM_NAME_LC}-${CMAKE_SYSTEM_PROCESSOR}/${CMAKE_CXX_COMPILER_ID_LC})

FIND_PATH(PTHREAD_INCLUDE_DIR pthread.h
  HINTS
  $ENV{PTHREADDIR}
  PATHS
  ${CONTRIB_HEADERS}/pthread # the headers we distribute
)

if(WIN32)
  if (MSVC)
	set(PTHREAD_LIB_NAME pthreadVC2)
  elseif(MINGW)
	set(PTHREAD_LIB_NAME pthreadGC2)
  endif()
endif()

FIND_LIBRARY(PTHREAD_LIBRARY 
  NAMES ${PTHREAD_LIB_NAME}
  HINTS
  $ENV{PTHREAD_LIB_DIR}
  PATHS
  ${PTHREAD_PREBUILT}
)

# handle the QUIETLY and REQUIRED arguments and set OPENAL_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PTHREAD  DEFAULT_MSG  PTHREAD_LIBRARY PTHREAD_INCLUDE_DIR)
MARK_AS_ADVANCED(PTHREAD_LIBRARY PTHREAD_INCLUDE_DIR)
